# Generated by Django 2.1 on 2019-04-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id')),
                ('subid', models.CharField(max_length=6, verbose_name='subid')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('countryId', models.CharField(max_length=50, verbose_name='countryId')),
                ('gender', models.CharField(max_length=1, verbose_name='gender')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
                'db_table': 'Persons',
                'ordering': ['id', 'subid'],
            },
        ),
        migrations.CreateModel(
            name='RanksAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personId', models.CharField(max_length=10, verbose_name='personId')),
                ('eventId', models.CharField(max_length=6, verbose_name='eventId')),
                ('best', models.IntegerField(verbose_name='best')),
                ('worldRank', models.IntegerField(verbose_name='worldRank')),
                ('continentRank', models.IntegerField(verbose_name='continentRank')),
                ('countryRank', models.IntegerField(verbose_name='countryRank')),
            ],
            options={
                'verbose_name': '名次平均',
                'verbose_name_plural': '名次平均',
                'db_table': 'RanksAverage',
                'ordering': ['eventId', 'worldRank'],
            },
        ),
        migrations.CreateModel(
            name='RanksSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personId', models.CharField(max_length=10, verbose_name='personId')),
                ('eventId', models.CharField(max_length=6, verbose_name='eventId')),
                ('best', models.IntegerField(verbose_name='best')),
                ('worldRank', models.IntegerField(verbose_name='worldRank')),
                ('continentRank', models.IntegerField(verbose_name='continentRank')),
                ('countryRank', models.IntegerField(verbose_name='countryRank')),
            ],
            options={
                'verbose_name': '名次单次',
                'verbose_name_plural': '名次单次',
                'db_table': 'RanksSingle',
                'ordering': ['eventId', 'worldRank'],
            },
        ),
    ]
